/* Name: ATI_HttpRequestParameter
Description : ATI_HttpRequestParameter Webservices
Author : Tavant(TY)
History:
VERSION     AUTHOR               DATE                    DETAIL                   UserStory/Req#
1.0 -     Tavant(TY)          Mar 15th 2021          INITIAL DEVELOPMENTs
*/
public class ATI_HttpRequestParameter {    
    public String endPoint;
    public String httpMethod;
    public String httpHeaderConType = 'Content-Type';
    public String httpHeaderConValue = 'application/json';
    public String httpHeaderReqId;
    public String httpHeaderReqValue;
    public String httpHeaderClientId;
    public String httpHeaderClientIdValue;
    public String httpHeaderClientSecret;
    public String httpHeaderClientSecretValue;
    public String httpHeaderAuthz;
    public String httpHeaderAuthVal;    
    public Integer httpTimeout;
    public String authKey;
    public String httpBody;
    
}