/* Name: ATI_TableComponentInterface
Description : Interface : Method -> queryRecords
Author : TAVANT
History:
VERSION     AUTHOR                 DATE                          UserStory/Req#
1.0 -     Tavant                01/12/2020                       20598                      
*/
public interface ATI_TableComponentInterface {
  //interface method queryRecords
  String queryRecords(WOD_2.QueryBuilderWrapper querybuilderObject);
}