/* Name: ATI_LogServiceWrapper
Description : Wrapper Class for log record
Author : Tavant (TY)
History :
VERSION      AUTHOR          DATE                  DETAIL                   UserStory/Req#
1.0 -       Tavant (TY)    24/11/2020         INITIAL DEVELOPMENT
*/
public class ATI_LogServiceWrapper {
    public String statusText;
    public String batchLogId;
    public String processName;
    public String errortext;
    public String identifier;
    public String primaryKey;
    public String inputRequestJSON;
    public String outputResponseJSON;
    public Integer failureRecordCount;
    public Integer successRecordCount;
    public Integer totalRecordCount;
}