/* Name: ATI_ValidateDetailPageInterface
Description : This class is used to build the query
Author : TAVANT
History:
VERSION     AUTHOR                 DATE                          UserStory/Req#
1.0 -     Tavant                01/12/2020                       20598                      
*/
public interface ATI_ValidateDetailPageInterface {
	//interface validateDetailPage method for different objects
	Boolean validateDetailPage(String recordId); 
}